# generated by datamodel-codegen:
#   filename:  audio-features.json
#   timestamp: 2023-07-18T17:42:21+00:00

from __future__ import annotations

from pydantic import BaseModel


class AudioFeaturesModel(BaseModel):
    danceability: float
    energy: float
    key: int
    loudness: float
    mode: int
    speechiness: float
    acousticness: float
    instrumentalness: float
    liveness: float
    valence: float
    tempo: float
    type: str
    id: str
    uri: str
    track_href: str
    analysis_url: str
    duration_ms: int
    time_signature: int
